version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=futuremessages"
      - "POSTGRES_PASSWORD=messages"
      - "POSTGRES_DB=futuremessages"
